const dayjs = require('dayjs');
const meterModel = require('../models/meterModel');
const pengaturanModel = require('../models/pengaturanModel');
const tagihanModel = require('../models/tagihanModel');
const tarifGolonganModel = require('../models/tarifGolonganModel');
const aplikasiModel = require('../models/aplikasiModel');
const whatsappService = require('./whatsappService');
const qrisService = require('./qrisService');
const { calculateBillTotals } = require('./billingService');

function clampDay(value, fallback, min = 1, max = 31) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return fallback;
  }

  return Math.max(min, Math.min(max, Math.trunc(numeric)));
}

function getCollectionWindow(settings) {
  const startDay = clampDay(settings?.tanggal_mulai_pencatatan, 1);
  const endDay = clampDay(settings?.tanggal_akhir_pencatatan, 25);

  return {
    startDay: Math.min(startDay, endDay),
    endDay: Math.max(startDay, endDay)
  };
}

function getAutoGenerateDay(settings) {
  return clampDay(settings?.tanggal_generate_otomatis, 1);
}

function isCollectionWindowOpen(settings, date = dayjs()) {
  const { startDay, endDay } = getCollectionWindow(settings);
  const currentDay = date.date();
  return currentDay >= startDay && currentDay <= endDay;
}

function getNextPeriod(bulan, tahun) {
  if (Number(bulan) >= 12) {
    return { bulan: 1, tahun: Number(tahun) + 1 };
  }

  return { bulan: Number(bulan) + 1, tahun: Number(tahun) };
}

function getPreviousPeriod(bulan, tahun) {
  if (Number(bulan) <= 1) {
    return { bulan: 12, tahun: Number(tahun) - 1 };
  }

  return { bulan: Number(bulan) - 1, tahun: Number(tahun) };
}

async function postProcessBill(tagihanId, settings, appConfig) {
  const bill = tagihanModel.getByIdDetail(tagihanId);
  if (!bill) {
    return { qrisPrepared: false, waSent: false };
  }

  let qrisPrepared = false;
  if (qrisService.isStaticQrisReady(appConfig)) {
    try {
      qrisService.ensureUniqueAmount(bill);
      qrisPrepared = true;
    } catch (error) {}
  }

  let waSent = false;
  try {
    waSent = await whatsappService.sendBillNotification(tagihanModel.getByIdDetail(tagihanId), settings);
  } catch (error) {}

  return { qrisPrepared, waSent };
}

async function generateBillsForReadingPeriod({
  sourceMonth,
  sourceYear,
  billingMonth,
  billingYear,
  generatedMode = 'manual'
}) {
  const readings = meterModel.listUnbilledByPeriod(sourceMonth, sourceYear);
  const settings = pengaturanModel.getSettings();
  const appConfig = aplikasiModel.getSettings();
  const result = {
    sourceMonth: Number(sourceMonth),
    sourceYear: Number(sourceYear),
    billingMonth: Number(billingMonth),
    billingYear: Number(billingYear),
    totalCandidates: readings.length,
    created: 0,
    skipped: 0,
    qrisPrepared: 0,
    waSent: 0,
    failed: []
  };

  for (const reading of readings) {
    try {
      // Ambil golongan pelanggan untuk tarif yang tepat
      const golongan = reading.golongan_id
        ? tarifGolonganModel.getByKode(reading.golongan_id)
        : null;

      const totals = calculateBillTotals({
        totalKubik: reading.total_kubik,
        settings,
        hasPreviousUnpaid: tagihanModel.hasPreviousUnpaid(reading.pelanggan_id),
        golongan
      });

      const tagihanId = tagihanModel.create({
        pencatatan_id: reading.id,
        bulan_tagihan: billingMonth,
        tahun_tagihan: billingYear,
        total_tagihan: totals.totalTagihan,
        denda: totals.denda,
        harga_per_kubik_snapshot: totals.hargaPerKubik,
        minimum_pemakaian_kubik_snapshot: totals.minimumPemakaianKubik,
        kubik_ditagihkan: totals.kubikDitagihkan,
        biaya_air: totals.biayaAir,
        biaya_admin_snapshot: totals.biayaAdmin,
        generated_mode: generatedMode
      });

      result.created += 1;

      const postProcess = await postProcessBill(tagihanId, settings, appConfig);
      if (postProcess.qrisPrepared) {
        result.qrisPrepared += 1;
      }
      if (postProcess.waSent) {
        result.waSent += 1;
      }
    } catch (error) {
      if (String(error.message || '').includes('UNIQUE constraint failed: tagihan.pencatatan_id')) {
        result.skipped += 1;
        continue;
      }

      result.failed.push({
        readingId: reading.id,
        pelangganId: reading.pelanggan_id,
        noMeteran: reading.no_meteran,
        nama: reading.nama,
        message: error.message
      });
    }
  }

  return result;
}

async function runAutomaticGeneration(referenceDate = dayjs()) {
  const settings = pengaturanModel.getSettings();
  const autoGenerateDay = getAutoGenerateDay(settings);
  if (referenceDate.date() < autoGenerateDay) {
    return {
      skipped: true,
      reason: 'before_auto_generate_day'
    };
  }

  const billingPeriod = {
    bulan: referenceDate.month() + 1,
    tahun: referenceDate.year()
  };
  const sourcePeriod = getPreviousPeriod(billingPeriod.bulan, billingPeriod.tahun);

  return generateBillsForReadingPeriod({
    sourceMonth: sourcePeriod.bulan,
    sourceYear: sourcePeriod.tahun,
    billingMonth: billingPeriod.bulan,
    billingYear: billingPeriod.tahun,
    generatedMode: 'auto'
  });
}

function startAutomaticGenerationScheduler() {
  runAutomaticGeneration().catch((error) => {
    console.error('Auto generate tagihan gagal saat startup:', error.message);
  });

  const interval = setInterval(() => {
    runAutomaticGeneration().catch((error) => {
      console.error('Auto generate tagihan gagal saat scheduler:', error.message);
    });
  }, 60 * 60 * 1000);

  if (typeof interval.unref === 'function') {
    interval.unref();
  }
}

module.exports = {
  getCollectionWindow,
  getAutoGenerateDay,
  isCollectionWindowOpen,
  getNextPeriod,
  getPreviousPeriod,
  generateBillsForReadingPeriod,
  runAutomaticGeneration,
  startAutomaticGenerationScheduler
};
