const dayjs = require('dayjs');
const QRCode = require('qrcode');
const pelangganModel = require('../models/pelangganModel');
const userModel = require('../models/userModel');
const aplikasiModel = require('../models/aplikasiModel');
const pengaturanModel = require('../models/pengaturanModel');
const tagihanModel = require('../models/tagihanModel');
const keuanganModel = require('../models/keuanganModel');
const pembayaranLogModel = require('../models/pembayaranLogModel');
const qrisNotifLogModel = require('../models/qrisNotifLogModel');
const dashboardService = require('../services/dashboardService');
const whatsappService = require('../services/whatsappService');
const qrisService = require('../services/qrisService');
const { processQrisAmount } = require('../services/qrisNotificationService');
const {
  getCollectionWindow,
  getAutoGenerateDay,
  getNextPeriod,
  getPreviousPeriod,
  generateBillsForReadingPeriod
} = require('../services/tagihanGenerationService');
const env = require('../config/env');

function getGenerationDefaults(referenceDate = dayjs()) {
  const billingPeriod = {
    bulan: referenceDate.month() + 1,
    tahun: referenceDate.year()
  };
  const sourcePeriod = getPreviousPeriod(billingPeriod.bulan, billingPeriod.tahun);
  const nextPeriod = getNextPeriod(billingPeriod.bulan, billingPeriod.tahun);

  return {
    sourcePeriod,
    billingPeriod,
    nextPeriod
  };
}

function getAdminRedirectTarget(value, fallback = '/admin') {
  if (typeof value !== 'string') {
    return fallback;
  }

  const trimmed = value.trim();
  if (!trimmed.startsWith('/admin')) {
    return fallback;
  }

  return trimmed;
}

function dashboard(req, res) {
  const settings = pengaturanModel.getSettings();
  return res.render('admin/dashboard', {
    title: 'Dashboard Admin',
    analytics: dashboardService.getDashboardData(),
    recentBills: tagihanModel.getRecentBills(10),
    recentFinance: keuanganModel.getLatest(10),
    billingSettings: settings,
    collectionWindow: getCollectionWindow(settings),
    autoGenerateDay: getAutoGenerateDay(settings),
    generationDefaults: getGenerationDefaults()
  });
}

function listTagihan(req, res) {
  const now = dayjs();
  const bulan = Number(req.query.bulan || (now.month() + 1));
  const tahun = Number(req.query.tahun || now.year());
  const status = String(req.query.status || 'all');
  const keyword = String(req.query.keyword || '');
  const limit = Number(req.query.limit || 200);

  const settings = pengaturanModel.getSettings();
  const bills = tagihanModel.listByPeriod({ bulan, tahun, status, keyword, limit });
  const summary = bills.reduce(
    (acc, item) => {
      acc.total += 1;
      if (item.status_bayar === 'lunas') {
        acc.lunas += 1;
      } else {
        acc.belum += 1;
      }
      return acc;
    },
    { total: 0, lunas: 0, belum: 0 }
  );

  return res.render('admin/tagihan-index', {
    title: 'Tagihan / Invoice',
    bulan,
    tahun,
    status,
    keyword,
    limit,
    summary,
    bills,
    billingSettings: settings,
    collectionWindow: getCollectionWindow(settings),
    autoGenerateDay: getAutoGenerateDay(settings),
    generationDefaults: getGenerationDefaults()
  });
}

function showTagihanDetail(req, res) {
  const tagihan = tagihanModel.getByIdDetail(req.params.id);
  if (!tagihan) {
    req.flash('danger', 'Tagihan tidak ditemukan.');
    return res.redirect('/admin/tagihan');
  }

  const breakdown = {
    periode: `${tagihan.bulan}/${tagihan.tahun}`,
    periodeBaca: `${tagihan.bulan_baca}/${tagihan.tahun_baca}`,
    meterAwal: tagihan.meteran_awal,
    meterAkhir: tagihan.meteran_akhir,
    totalKubik: tagihan.total_kubik,
    kubikDitagihkan: tagihan.kubik_ditagihkan || tagihan.total_kubik,
    hargaPerKubik: tagihan.harga_per_kubik_snapshot,
    minimumPemakaianKubik: tagihan.minimum_pemakaian_kubik_snapshot,
    biayaAir: tagihan.biaya_air,
    biayaAdmin: tagihan.biaya_admin_snapshot,
    denda: tagihan.denda || 0,
    totalTagihan: tagihan.total_tagihan
  };

  return res.render('admin/tagihan-detail', {
    title: `Invoice ${tagihan.no_meteran} ${tagihan.bulan}/${tagihan.tahun}`,
    tagihan,
    breakdown
  });
}

function listPelanggan(req, res) {
  return res.render('admin/pelanggan-index', {
    title: 'Data Pelanggan',
    pelanggan: pelangganModel.listAll()
  });
}

function listPetugas(req, res) {
  return res.render('admin/petugas-index', {
    title: 'Manajemen Petugas',
    petugas: userModel.listStaff()
  });
}

function showCreatePetugas(req, res) {
  return res.render('admin/petugas-form', {
    title: 'Tambah Petugas',
    formAction: '/admin/petugas',
    petugas: null
  });
}

function showEditPetugas(req, res) {
  const petugas = userModel.findByIdFull(req.params.id);
  if (!petugas || petugas.role === 'admin' || petugas.role === 'pelanggan') {
    req.flash('danger', 'Data petugas tidak ditemukan.');
    return res.redirect('/admin/petugas');
  }

  return res.render('admin/petugas-form', {
    title: 'Edit Petugas',
    formAction: `/admin/petugas/${petugas.id}`,
    petugas
  });
}

function storePetugas(req, res) {
  try {
    if (!['catter', 'kasir'].includes(req.body.role)) {
      req.flash('danger', 'Role petugas tidak valid.');
      return res.redirect('/admin/petugas/new');
    }

    if (!req.body.password) {
      req.flash('danger', 'Password wajib diisi untuk petugas baru.');
      return res.redirect('/admin/petugas/new');
    }

    userModel.createUser({
      username: req.body.username,
      password: req.body.password,
      role: req.body.role
    });

    req.flash('success', 'Petugas berhasil ditambahkan.');
    return res.redirect('/admin/petugas');
  } catch (error) {
    req.flash('danger', error.message);
    return res.redirect('/admin/petugas/new');
  }
}

function updatePetugas(req, res) {
  const petugas = userModel.findByIdFull(req.params.id);
  if (!petugas || petugas.role === 'admin' || petugas.role === 'pelanggan') {
    req.flash('danger', 'Data petugas tidak ditemukan.');
    return res.redirect('/admin/petugas');
  }

  try {
    if (!['catter', 'kasir'].includes(req.body.role)) {
      req.flash('danger', 'Role petugas tidak valid.');
      return res.redirect(`/admin/petugas/${petugas.id}/edit`);
    }

    userModel.updateUser({
      id: petugas.id,
      username: req.body.username,
      password: req.body.password,
      role: req.body.role
    });

    req.flash('success', 'Data petugas berhasil diperbarui.');
    return res.redirect('/admin/petugas');
  } catch (error) {
    req.flash('danger', error.message);
    return res.redirect(`/admin/petugas/${petugas.id}/edit`);
  }
}

function deletePetugas(req, res) {
  const petugas = userModel.findByIdFull(req.params.id);
  if (!petugas || petugas.role === 'admin' || petugas.role === 'pelanggan') {
    req.flash('danger', 'Data petugas tidak ditemukan.');
    return res.redirect('/admin/petugas');
  }

  try {
    userModel.deleteById(petugas.id);
    req.flash('success', 'Petugas berhasil dihapus.');
  } catch (error) {
    req.flash('danger', 'Petugas tidak bisa dihapus karena masih terhubung dengan data transaksi.');
  }

  return res.redirect('/admin/petugas');
}

function showCreatePelanggan(req, res) {
  return res.render('admin/pelanggan-form', {
    title: 'Tambah Pelanggan',
    formAction: '/admin/pelanggan',
    pelanggan: null
  });
}

function showEditPelanggan(req, res) {
  const pelanggan = pelangganModel.getById(req.params.id);
  if (!pelanggan) {
    req.flash('danger', 'Data pelanggan tidak ditemukan.');
    return res.redirect('/admin/pelanggan');
  }

  return res.render('admin/pelanggan-form', {
    title: 'Edit Pelanggan',
    formAction: `/admin/pelanggan/${pelanggan.id}`,
    pelanggan
  });
}

function storePelanggan(req, res) {
  try {
    const { no_meteran, nama, alamat, no_whatsapp, tgl_bergabung, username, password } = req.body;
    let userId = null;

    if (username && !password) {
      req.flash('danger', 'Password wajib diisi saat membuat login pelanggan.');
      return res.redirect('/admin/pelanggan/new');
    }

    if (username && password) {
      userId = userModel.upsertPelangganLogin({ username, password });
    }

    pelangganModel.create({
      no_meteran,
      nama,
      alamat,
      no_whatsapp,
      tgl_bergabung,
      user_id: userId
    });

    req.flash('success', 'Pelanggan berhasil ditambahkan.');
    return res.redirect('/admin/pelanggan');
  } catch (error) {
    req.flash('danger', error.message);
    return res.redirect('/admin/pelanggan/new');
  }
}

function updatePelanggan(req, res) {
  const current = pelangganModel.getById(req.params.id);
  if (!current) {
    req.flash('danger', 'Data pelanggan tidak ditemukan.');
    return res.redirect('/admin/pelanggan');
  }

  try {
    const { no_meteran, nama, alamat, no_whatsapp, tgl_bergabung, username, password } = req.body;
    let userId = current.user_id;

    if (username) {
      if (!userId && !password) {
        req.flash('danger', 'Password wajib diisi saat pertama kali membuat login pelanggan.');
        return res.redirect(`/admin/pelanggan/${current.id}/edit`);
      }

      userId = userModel.upsertPelangganLogin({
        userId,
        username,
        password
      });
    }

    pelangganModel.update(current.id, {
      no_meteran,
      nama,
      alamat,
      no_whatsapp,
      tgl_bergabung,
      user_id: userId
    });

    req.flash('success', 'Data pelanggan berhasil diperbarui.');
    return res.redirect('/admin/pelanggan');
  } catch (error) {
    req.flash('danger', error.message);
    return res.redirect(`/admin/pelanggan/${current.id}/edit`);
  }
}

function deletePelanggan(req, res) {
  const pelanggan = pelangganModel.getById(req.params.id);
  if (!pelanggan) {
    req.flash('danger', 'Data pelanggan tidak ditemukan.');
    return res.redirect('/admin/pelanggan');
  }

  pelangganModel.remove(pelanggan.id);
  if (pelanggan.user_id) {
    userModel.deleteById(pelanggan.user_id);
  }

  req.flash('success', 'Pelanggan berhasil dihapus.');
  return res.redirect('/admin/pelanggan');
}

async function showPelangganQr(req, res) {
  const pelanggan = pelangganModel.getById(req.params.id);
  if (!pelanggan) {
    req.flash('danger', 'Data pelanggan tidak ditemukan.');
    return res.redirect('/admin/pelanggan');
  }

  const qrValue = `${env.baseUrl}/pelanggan/cek?keyword=${encodeURIComponent(pelanggan.no_meteran)}`;
  const qrDataUrl = await QRCode.toDataURL(qrValue);

  return res.render('admin/pelanggan-qr', {
    title: 'QR Pelanggan',
    pelanggan,
    qrDataUrl,
    qrValue
  });
}

function showSettings(req, res) {
  const qrisStatus = req.query.qris_status || 'all';
  const settings = pengaturanModel.getSettings();
  return res.render('admin/pengaturan', {
    title: 'Pengaturan Harga & Keuangan',
    appConfig: aplikasiModel.getSettings(),
    settings,
    financeEntries: keuanganModel.getLatest(20),
    qrisNotifLogs: qrisNotifLogModel.getFiltered(qrisStatus, 20),
    qrisLogSummary: qrisNotifLogModel.getSummary(),
    qrisStatus,
    collectionWindow: getCollectionWindow(settings),
    autoGenerateDay: getAutoGenerateDay(settings),
    generationDefaults: getGenerationDefaults()
  });
}

function assignQrisCode(req, res) {
  const tagihan = tagihanModel.getByIdDetail(req.params.id);
  if (!tagihan) {
    req.flash('danger', 'Tagihan tidak ditemukan.');
    return res.redirect('/admin');
  }

  if (tagihan.status_bayar === 'lunas') {
    req.flash('warning', 'Tagihan sudah lunas.');
    return res.redirect('/admin');
  }

  if (String(req.query.force || '') === '1') {
    tagihanModel.clearQrisUnique(tagihan.id);
  }

  try {
    qrisService.ensureUniqueAmount(tagihanModel.getByIdDetail(tagihan.id));
    req.flash('success', 'Kode unik QRIS berhasil disiapkan.');
  } catch (error) {
    req.flash('danger', error.message);
  }

  return res.redirect('/admin');
}

function clearQrisCode(req, res) {
  const tagihan = tagihanModel.getByIdDetail(req.params.id);
  if (!tagihan) {
    req.flash('danger', 'Tagihan tidak ditemukan.');
    return res.redirect('/admin');
  }

  tagihanModel.clearQrisUnique(tagihan.id);
  req.flash('success', 'Kode unik QRIS berhasil dihapus.');
  return res.redirect('/admin');
}

async function retryQrisLog(req, res) {
  const log = qrisNotifLogModel.getById(req.params.id);
  const appConfig = aplikasiModel.getSettings();

  if (!log) {
    req.flash('danger', 'Log QRIS tidak ditemukan.');
    return res.redirect('/admin/pengaturan');
  }

  if (!log.amount_detected) {
    req.flash('warning', 'Log ini tidak memiliki nominal yang bisa dicocokkan ulang.');
    return res.redirect('/admin/pengaturan');
  }

  if (log.match_status === 'matched') {
    req.flash('info', 'Log ini sudah pernah berhasil dicocokkan.');
    return res.redirect('/admin/pengaturan');
  }

  const result = await processQrisAmount(log.amount_detected, appConfig.qris_match_window_minutes);
  if (!result.matched) {
    req.flash('warning', 'Retry match belum menemukan tagihan yang sesuai.');
    return res.redirect('/admin/pengaturan');
  }

  qrisNotifLogModel.finish({
    payload_hash: log.payload_hash,
    amount_detected: log.amount_detected,
    message_text: log.message_text,
    sender: log.sender,
    matched_tagihan_id: result.bill.id,
    match_status: result.match_status,
    match_reason: 'manual_retry_match'
  });

  req.flash('success', `Log QRIS berhasil dicocokkan ke tagihan ${result.bill.no_meteran}.`);
  return res.redirect('/admin/pengaturan');
}

function updateSettings(req, res) {
  const redirectTarget = getAdminRedirectTarget(req.body.redirect_to, '/admin/pengaturan');
  pengaturanModel.updateSettings({
    id: req.body.id,
    harga_per_kubik: Number(req.body.harga_per_kubik || 0),
    minimum_pemakaian_kubik: Number(req.body.minimum_pemakaian_kubik || 0),
    tanggal_mulai_pencatatan: Number(req.body.tanggal_mulai_pencatatan || 1),
    tanggal_akhir_pencatatan: Number(req.body.tanggal_akhir_pencatatan || 25),
    tanggal_generate_otomatis: Number(req.body.tanggal_generate_otomatis || 1),
    biaya_admin: Number(req.body.biaya_admin || 0),
    denda_keterlambatan: Number(req.body.denda_keterlambatan || 0)
  });

  req.flash('success', 'Pengaturan tarif berhasil disimpan.');
  return res.redirect(redirectTarget);
}

async function generateBillsManual(req, res) {
  const redirectTarget = getAdminRedirectTarget(req.body.redirect_to, '/admin');
  const sourceMonth = Number(req.body.source_month || 0);
  const sourceYear = Number(req.body.source_year || 0);
  const billingMonthInput = Number(req.body.billing_month || 0);
  const billingYearInput = Number(req.body.billing_year || 0);

  if (!sourceMonth || sourceMonth < 1 || sourceMonth > 12 || !sourceYear) {
    req.flash('danger', 'Periode pencatatan tidak valid.');
    return res.redirect(redirectTarget);
  }

  const computedBilling = getNextPeriod(sourceMonth, sourceYear);
  const billingMonth = billingMonthInput >= 1 && billingMonthInput <= 12 ? billingMonthInput : computedBilling.bulan;
  const billingYear = billingYearInput || computedBilling.tahun;

  const result = await generateBillsForReadingPeriod({
    sourceMonth,
    sourceYear,
    billingMonth,
    billingYear,
    generatedMode: 'manual'
  });

  if (!result.totalCandidates) {
    req.flash('warning', `Tidak ada data pencatatan periode ${sourceMonth}/${sourceYear} yang siap digenerate.`);
    return res.redirect(redirectTarget);
  }

  const failureText = result.failed.length ? ` Gagal: ${result.failed.length}.` : '';
  req.flash(
    'success',
    `Generate tagihan manual ${sourceMonth}/${sourceYear} ke periode tagihan ${billingMonth}/${billingYear} selesai. Dibuat: ${result.created}, Skip: ${result.skipped}, QRIS siap: ${result.qrisPrepared}, WA terkirim: ${result.waSent}.${failureText}`
  );
  return res.redirect(redirectTarget);
}

function updateAppConfig(req, res) {
  const currentConfig = aplikasiModel.getSettings();
  const qrisFile = req.files && req.files.qris_static_qr && req.files.qris_static_qr[0] ? req.files.qris_static_qr[0] : null;
  const logoFile = req.files && req.files.logo && req.files.logo[0] ? req.files.logo[0] : null;

  const qrisStaticQrUrl = qrisFile
    ? `/uploads/qris/${qrisFile.filename}`
    : (req.body.current_qris_static_qr_url || currentConfig?.qris_static_qr_url || '');

  const logoUrl = logoFile
    ? `/uploads/logo/${logoFile.filename}`
    : (req.body.current_logo_url || currentConfig?.logo_url || '');

  aplikasiModel.updateSettings({
    id: req.body.id,
    nama_aplikasi: req.body.nama_aplikasi,
    nama_instansi: req.body.nama_instansi,
    logo_url: logoUrl,
    alamat_loket: req.body.alamat_loket,
    no_whatsapp_loket: req.body.no_whatsapp_loket,
    footer_kwitansi: req.body.footer_kwitansi,
    base_url_public: req.body.base_url_public,
    public_home_headline: req.body.public_home_headline,
    public_home_tagline: req.body.public_home_tagline,
    public_profile_text: req.body.public_profile_text,
    public_payment_info_text: req.body.public_payment_info_text,
    public_service_hours_text: req.body.public_service_hours_text,
    qris_static_enabled: req.body.qris_static_enabled === '1',
    qris_static_qr_url: qrisStaticQrUrl,
    qris_static_payload: req.body.qris_static_payload,
    qris_admin_wa: req.body.qris_admin_wa,
    qris_help_text: req.body.qris_help_text,
    qris_webhook_token: req.body.qris_webhook_token,
    qris_match_window_minutes: req.body.qris_match_window_minutes,
    qris_send_wa_image: req.body.qris_send_wa_image === '1',
    wa_template_qris_tagihan: req.body.wa_template_qris_tagihan
  });

  req.flash('success', 'Pengaturan aplikasi berhasil disimpan.');
  return res.redirect('/admin/pengaturan');
}

function addExpense(req, res) {
  keuanganModel.createEntry({
    tipe: 'pengeluaran',
    jumlah: Number(req.body.jumlah || 0),
    keterangan: req.body.keterangan,
    tanggal: req.body.tanggal
  });

  req.flash('success', 'Pengeluaran berhasil dicatat.');
  return res.redirect('/admin/pengaturan');
}

async function markBillPaid(req, res) {
  const tagihan = tagihanModel.getByIdDetail(req.params.id);
  if (!tagihan) {
    req.flash('danger', 'Tagihan tidak ditemukan.');
    return res.redirect('/admin');
  }

  if (tagihan.status_bayar === 'lunas') {
    req.flash('warning', 'Tagihan sudah berstatus lunas.');
    return res.redirect('/admin');
  }

  tagihanModel.markPaid(tagihan.id, req.body.metode_bayar || 'manual');
  keuanganModel.createEntry({
    tipe: 'pemasukan',
    jumlah: tagihan.total_tagihan,
    keterangan: `Pembayaran tagihan ${tagihan.nama} periode ${tagihan.bulan}/${tagihan.tahun}`
  });
  pembayaranLogModel.create({
    tagihan_id: tagihan.id,
    user_id: req.session.user.id,
    jumlah_bayar: tagihan.total_tagihan,
    metode_bayar: req.body.metode_bayar || 'manual',
    keterangan: 'Pelunasan dari panel admin'
  });

  const updatedBill = tagihanModel.getByIdDetail(tagihan.id);
  await whatsappService.sendPaymentReceipt(updatedBill);

  req.flash('success', 'Tagihan berhasil ditandai lunas.');
  return res.redirect('/admin');
}

async function showWhatsapp(req, res) {
  return res.render('admin/whatsapp', {
    title: 'WhatsApp Gateway',
    whatsapp: whatsappService.getWhatsappState()
  });
}

async function reconnectWhatsapp(req, res) {
  await whatsappService.initWhatsapp();
  req.flash('success', 'Proses koneksi WhatsApp dijalankan ulang.');
  return res.redirect('/admin/whatsapp');
}

async function broadcastWhatsapp(req, res) {
  const recipients = pelangganModel.listWhatsappRecipients();
  const result = await whatsappService.broadcastAnnouncement(recipients, req.body.pesan);
  const totalSent = result.filter((item) => item.sent).length;

  req.flash('success', `Broadcast selesai. ${totalSent} dari ${result.length} pesan berhasil dikirim.`);
  return res.redirect('/admin/whatsapp');
}

async function sendQrisToCustomer(req, res) {
  const tagihan = tagihanModel.getByIdDetail(req.params.id);
  if (!tagihan) {
    req.flash('danger', 'Tagihan tidak ditemukan.');
    return res.redirect('/admin');
  }

  const sent = await whatsappService.sendQrisPaymentRequest(tagihan);
  if (!sent) {
    req.flash('warning', 'Gagal mengirim QRIS via WhatsApp. Pastikan WA terhubung, QRIS aktif, dan nomor pelanggan terisi.');
    return res.redirect('/admin');
  }

  req.flash('success', 'QRIS berhasil dikirim ke pelanggan via WhatsApp.');
  return res.redirect('/admin');
}

async function sendQrisReminderBulk(req, res) {
  const bulan = Number(req.body.bulan || 0);
  const tahun = Number(req.body.tahun || 0);
  if (!bulan || !tahun) {
    req.flash('danger', 'Periode tidak valid.');
    return res.redirect('/admin/whatsapp');
  }

  const bills = tagihanModel.listUnpaidByPeriod(bulan, tahun);
  let sentCount = 0;
  let failCount = 0;

  for (const bill of bills) {
    try {
      const ok = await whatsappService.sendQrisPaymentRequest(bill);
      if (ok) {
        sentCount += 1;
      } else {
        failCount += 1;
      }
    } catch (error) {
      failCount += 1;
    }
  }

  req.flash('success', `Reminder QRIS selesai. Berhasil: ${sentCount}, Gagal: ${failCount}, Total: ${bills.length}.`);
  return res.redirect('/admin/whatsapp');
}

async function testQrisWhatsapp(req, res) {
  const appConfig = aplikasiModel.getSettings();
  const to = appConfig?.qris_admin_wa || appConfig?.no_whatsapp_loket || '';
  const text = `${appConfig?.nama_instansi || appConfig?.nama_aplikasi || 'PAMSIMAS'}\n\nTest WhatsApp QRIS berhasil.`;
  const ok = await whatsappService.sendTextMessage(to, text);

  if (!ok) {
    req.flash('warning', 'Gagal mengirim pesan test. Pastikan WA terhubung dan nomor admin QRIS/WA loket diisi.');
    return res.redirect('/admin/whatsapp');
  }

  req.flash('success', 'Pesan test WhatsApp berhasil dikirim.');
  return res.redirect('/admin/whatsapp');
}

module.exports = {
  dashboard,
  listTagihan,
  showTagihanDetail,
  listPelanggan,
  listPetugas,
  showCreatePetugas,
  showEditPetugas,
  storePetugas,
  updatePetugas,
  deletePetugas,
  showCreatePelanggan,
  showEditPelanggan,
  storePelanggan,
  updatePelanggan,
  deletePelanggan,
  showPelangganQr,
  showSettings,
  updateSettings,
  generateBillsManual,
  updateAppConfig,
  assignQrisCode,
  clearQrisCode,
  retryQrisLog,
  addExpense,
  markBillPaid,
  showWhatsapp,
  reconnectWhatsapp,
  broadcastWhatsapp,
  sendQrisToCustomer,
  sendQrisReminderBulk,
  testQrisWhatsapp
};
