const pengaturanModel = require('../models/pengaturanModel');
const dashboardService = require('../services/dashboardService');
const { getCollectionWindow, getAutoGenerateDay } = require('../services/tagihanGenerationService');

function showHome(req, res) {
  const pricing = pengaturanModel.getSettings();
  const collectionWindow = getCollectionWindow(pricing);
  const autoGenerateDay = getAutoGenerateDay(pricing);
  const summary = dashboardService.getDashboardData().summary;

  const currentUser = req.session.user || null;
  let dashboardUrl = '';
  if (currentUser?.role === 'admin') {
    dashboardUrl = '/admin';
  } else if (currentUser?.role === 'catter') {
    dashboardUrl = '/catter';
  } else if (currentUser?.role === 'kasir') {
    dashboardUrl = '/kasir';
  } else if (currentUser?.role === 'pelanggan') {
    dashboardUrl = '/pelanggan';
  }

  return res.render('public/home', {
    title: res.locals.appConfig?.nama_aplikasi || 'PAMSIMAS',
    pricing,
    collectionWindow,
    autoGenerateDay,
    summary,
    dashboardUrl
  });
}

module.exports = {
  showHome
};

